import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  raiz: { flex: 1, justifyContent: 'flex-end' },
  fundo: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.45)' },

  folha: {
    height: '88%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    overflow: 'hidden',
  },
  folhaTopo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  folhaTitulo: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  loading: { flex: 1 },
  conteudo: { padding: 20, paddingBottom: 40 },

  linhaTopo: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  tipo: { flex: 1, fontSize: 20, fontWeight: 'bold', color: '#222', marginRight: 8 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12 },
  statusTexto: { color: '#fff', fontSize: 11, fontWeight: 'bold', textTransform: 'capitalize' },
  meta: { fontSize: 12, color: '#888', marginTop: 4 },
  descricao: { fontSize: 15, color: '#444', marginTop: 12 },

  fotoBloco: { marginTop: 12 },
  foto: { width: '100%', height: 190, borderRadius: 12, backgroundColor: '#eee' },
  fotoCredito: { fontSize: 11, color: '#888', marginTop: 4 },
  removerFoto: { position: 'absolute', top: 6, right: 6 },

  upBotao: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    height: 46,
    borderRadius: 23,
    borderWidth: 1.5,
    borderColor: '#ff7b39',
    backgroundColor: '#fff',
  },
  upBotaoAtivo: { backgroundColor: '#ff7b39' },
  upTexto: { marginLeft: 6, fontSize: 15, fontWeight: 'bold', color: '#ff7b39' },
  upTextoAtivo: { color: '#fff' },

  secao: { fontSize: 17, fontWeight: 'bold', color: '#333', marginTop: 24 },
  vazio: { fontSize: 13, color: '#999', marginTop: 8 },

  atualizacao: {
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#f6f6f6',
  },
  atualizacaoTopo: { flexDirection: 'row', justifyContent: 'space-between' },
  atualizacaoAutor: { flex: 1, fontSize: 14, fontWeight: 'bold', color: '#333', marginRight: 8 },
  atualizacaoData: { fontSize: 11, color: '#999' },
  atualizacaoTexto: { fontSize: 14, color: '#444', marginTop: 8 },
  chipFixo: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: '#ff7b39',
  },
  chipFixoTexto: { color: '#fff', fontSize: 11, fontWeight: 'bold' },

  chips: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#ddd',
    marginRight: 8,
    marginBottom: 8,
  },
  chipAtivo: { backgroundColor: '#ff7b39', borderColor: '#ff7b39' },
  chipTexto: { fontSize: 13, fontWeight: '600', color: '#666' },
  chipTextoAtivo: { color: '#fff' },

  textarea: {
    minHeight: 90,
    marginTop: 4,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    fontSize: 14,
    color: '#222',
    textAlignVertical: 'top',
  },
  anexar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
  },
  anexarTexto: { marginLeft: 6, fontSize: 13, fontWeight: '600', color: '#333' },

  enviar: {
    marginTop: 18,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#ff4b4b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  enviarDesabilitado: { opacity: 0.5 },
  enviarTexto: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
});